//Please use capitals naming for making types
export default {
    SWITCH_ROUTE: "SWITCH_ROUTE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    SPLASHLOADING: "AUTH_SPLASHLOADING",
    CHALLENGE_ID: "CHALLENGE_ID",
    USER_DETAILS: "USER_DETAILS",
    LANGUAGE: "LANGUAGE",
    SET_REFRESH_TOKEN: "SET_REFRESH_TOKEN",
    LAST_DISPATCHED_ACTION: "LAST_DISPATCHED_ACTION",
    TURN_OFF_ALL_LOADER: "TURN_OFF_ALL_LOADER",
    API_ERROR_MESSAGE: "API_ERROR_MESSAGE",
    EMAIL: "EMAIL",
    LOGOUT: "LOGOUT",
    STORE_EMAIL: "STORE_EMAIL"
}