//Please use capitals naming for making types
export default {
    MENU_LIST: 'MENU_LIST',
    HANDLE_MENU_LOADER: "HANDLE_MENU_LOADER",
    SET_SELECTED_TIMESLOT: "SET_SELECTED_TIMESLOT",
    SET_SELECTED_DELIVERY_AND_SLOT: "SET_SELECTED_DELIVERY_AND_SLOT",
    SET_SELECTED_DAY_SLOT_AND_PRODUCT: "SET_SELECTED_DAY_SLOT_AND_PRODUCT",
    INCREASE_DECREASE_BASKET_QUANTITY_PRODUCT: "INCREASE_DECREASE_BASKET_QUANTITY_PRODUCT",
    SET_MEAL_OVERVIEW_DATA: "SET_MEAL_OVERVIEW_DATA",
    RESET_MENU_DATA_AFTER_PLACE_ORDER: "RESET_MENU_DATA_AFTER_PLACE_ORDER",
    PULL_ON_REFRESH_LOADER: "PULL_ON_REFRESH_LOADER"
}