export default {
    BASKET_LIST: "BASKET_LIST",
    HANLDE_LOADER_ADD_REMOVE_BASKET: "HANLDE_LOADER_ADD_REMOVE_BASKET",
    ADD_REMOVE_BASKET_QUANTITY: "ADD_REMOVE_BASKET_QUANTITY",
    CLEAR_BASKET_DATA_ON_LOGOUT: "CLEAR_BASKET_DATA_ON_LOGOUT",
    PROMO_CODE: "PROMO_CODE",
    UPDATE_BASKET_LIST: "UPDATE_BASKET_LIST",
    COME_PROMO_CODE: "COME_PROMO_CODE"
}