export default {
    ANALYTICS_TYPE_ACTION : 'ACTION',
    ANALYTICS_TYPE_PROCESS : 'PROCESS',

    //LOGIN SCREEN
    ANALYTICS_LOGIN_CONTINUE : 'LOGIN_CONTINUE',
    
    //OTP SCREEN
    ANALYTICS_VERIFY_RESEND : 'VERIFY_RESEND',
    ANALYTICS_VERIFY_OTP_REQUEST : 'VERIFY_VERIFY_REQUEST',
    ANALYTICS_VERIFY_OTP_SUCCESSFULL : 'VERIFY_OTP_SUCCESSFULL',
    
    //MENU SCREEN
    ANALYTICS_MENU_REFRESH_LIST: 'MENU_REFRESH_LIST',

    //ACCOUNT SCREEN
    ANALYTICS_LOGOUT : 'LOGOUT',


}