//Please use camel case for naming convention.
export default {
    poppinsBlack: "Poppins-Black",
    poppinsBlackItalic: "Poppins-BlackItalic",
    poppinsBold: "Poppins-Bold",
    poppinsBoldItalic: "Poppins-BoldItalic",
    poppinsExtraBold: "Poppins-ExtraBold",
    poppinsExtraBoldItalic: "Poppins-ExtraBoldItalic",
    poppinsExtraLight: "Poppins-ExtraLight",
    poppinsExtraLightItalic: "Poppins-ExtraLightItalic",
    poppinsItalic: "Poppins-Italic",
    poppinsLight: "Poppins-Light",
    poppinsLightItalic: "Poppins-LightItalic",
    poppinsMedium: "Poppins-Medium",
    poppinsMediumItalic: "Poppins-MediumItalic",
    poppinsRegular: "Poppins-Regular",
    poppinsSemiBold: "Poppins-SemiBold",
    poppinsSemiBoldItalic: "Poppins-SemiBoldItalic",
    poppinsThin: "Poppins-Thin",
    poppinsThinItalic: "Poppins-ThinItalic",
    interBlack: "Inter-Black",
    interBold: "Inter-Bold",
    interExtraBold: "Inter-ExtraBold",
    interExtraLight: "Inter-ExtraLight",
    interLight: "Inter-Light",
    interMedium: "Inter-Medium",
    interRegular: "Inter-Regular",
    interSemiBold: "Inter-SemiBold",
    interThin: "Inter-Thin",
    splineSans: "SplineSans-VariableFont_wght",
    CheltenhamstdBook: "Cheltenhamstd-Book"
}